//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPhaseEndProject2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PHASEENDPP2Entities : DbContext
    {
        public PHASEENDPP2Entities()
            : base("name=PHASEENDPP2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GamingLaptop> GamingLaptops { get; set; }
        public virtual DbSet<StudentLaptop> StudentLaptops { get; set; }
    }
}
